[package]
name = "xmcs"
version = "0.1.0"
authors = ["Jean-Baptiste Daval <j-b.daval@crans.org>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
